version: "3.8"

services:
  mcp-servers:
    build:
      context: ./src/mcp-servers
      target: development
    volumes:
      - ./src/mcp-servers:/app
      - /app/node_modules
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
      - "3004:3004"
      - "3005:3005"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - LOG_LEVEL=debug
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    depends_on:
      - ui

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./ui:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3002

volumes:
  node_modules:
