version: "3.8"

services:
  mcp-servers:
    build:
      target: development
    volumes:
      - ./src/mcp-servers:/app
      - ./src/mcp-servers/node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - DEBUG=*

  ui:
    build:
      target: dev
    volumes:
      - ./ui:/app
      - ./ui/node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - DEBUG=*
      - NEXT_PUBLIC_API_URL=http://localhost:3002
