version: "3.8"

services:
  mcp-servers:
    build:
      target: production
    restart: always
    environment:
      - NODE_ENV=production

  ui:
    build:
      target: production
    restart: always
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:3002

  # Add a reverse proxy in production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ui
      - mcp-servers
